PRAGMA foreign_keys = OFF;
-- BEGIN TRANSACTION;
ANALYZE sqlite_schema;
-- attach database 'F:\\Projects\\FEEDistri\\DataBase\\Calibration.db' as caliDB;
CREATE TABLE FEEBOARD(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL UNIQUE,
    -- AMP Table entry
    AmpTableEntry INT NOT NULL UNIQUE,
    -- Bias Table entry
    BiasTableEntry INT NOT NULL UNIQUE
);
CREATE TABLE AMPTABLE(
    ID INT PRIMARY KEY NOT NULL UNIQUE,
    BoardNo INT,
    AmpSet0Entry INT,
    AmpSet1Entry INT,
    AmpSet2Entry INT,
    AmpSet3Entry INT,
    AmpSet4Entry INT,
    AmpSet5Entry INT,
    AmpSet6Entry INT,
    AmpSet7Entry INT,
    AmpSet8Entry INT,
    AmpSet9Entry INT,
    AmpSet10Entry INT,
    AmpSet11Entry INT,
    AmpSet12Entry INT,
    AmpSet13Entry INT,
    AmpSet14Entry INT,
    AmpSet15Entry INT,
    AmpSet16Entry INT,
    AmpSet17Entry INT,
    AmpSet18Entry INT,
    AmpSet19Entry INT,
    AmpSet20Entry INT,
    AmpSet21Entry INT,
    AmpSet22Entry INT,
    AmpSet23Entry INT,
    AmpSet24Entry INT,
    AmpSet25Entry INT,
    AmpSet26Entry INT,
    AmpSet27Entry INT,
    AmpSet28Entry INT,
    AmpSet29Entry INT,
    AmpSet30Entry INT,
    AmpSet31Entry INT,
    AmpSet32Entry INT,
    AmpSet33Entry INT,
    AmpSet34Entry INT,
    AmpSet35Entry INT,
    AmpSet36Entry INT,
    AmpSet37Entry INT,
    AmpSet38Entry INT,
    AmpSet39Entry INT,
    AmpSet40Entry INT,
    AmpSet41Entry INT,
    AmpSet42Entry INT,
    AmpSet43Entry INT,
    AmpSet44Entry INT,
    AmpSet45Entry INT,
    AmpSet46Entry INT,
    AmpSet47Entry INT,
    AmpSet48Entry INT,
    AmpSet49Entry INT,
    AmpSet50Entry INT,
    AmpSet51Entry INT,
    AmpSet52Entry INT,
    AmpSet53Entry INT,
    AmpSet54Entry INT,
    AmpSet55Entry INT,
    AmpSet56Entry INT,
    AmpSet57Entry INT,
    AmpSet58Entry INT,
    AmpSet59Entry INT,
    AmpSet60Entry INT,
    AmpSet61Entry INT,
    AmpSet62Entry INT
);
CREATE TABLE BIASTABLE(
    ID INT PRIMARY KEY NOT NULL UNIQUE,
    BoardNo INT,
    BiasAt0Entry INT,
    BiasAt1Entry INT,
    BiasAt2Entry INT,
    BiasAt3Entry INT,
    BiasAt4Entry INT,
    BiasAt5Entry INT,
    BiasAt6Entry INT,
    BiasAt7Entry INT,
    BiasAt8Entry INT,
    BiasAt9Entry INT,
    BiasAt10Entry INT,
    BiasAt11Entry INT,
    BiasAt12Entry INT,
    BiasAt13Entry INT,
    BiasAt14Entry INT,
    BiasAt15Entry INT,
    BiasAt16Entry INT,
    BiasAt17Entry INT,
    BiasAt18Entry INT,
    BiasAt19Entry INT,
    BiasAt20Entry INT,
    BiasAt21Entry INT,
    BiasAt22Entry INT,
    BiasAt23Entry INT,
    BiasAt24Entry INT,
    BiasAt25Entry INT,
    BiasAt26Entry INT,
    BiasAt27Entry INT,
    BiasAt28Entry INT,
    BiasAt29Entry INT,
    BiasAt30Entry INT,
    BiasAt31Entry INT,
    BiasAt32Entry INT,
    BiasAt33Entry INT,
    BiasAt34Entry INT,
    BiasAt35Entry INT,
    BiasAt36Entry INT,
    BiasAt37Entry INT,
    BiasAt38Entry INT,
    BiasAt39Entry INT,
    BiasAt40Entry INT,
    BiasAt41Entry INT,
    BiasAt42Entry INT,
    BiasAt43Entry INT,
    BiasAt44Entry INT,
    BiasAt45Entry INT,
    BiasAt46Entry INT,
    BiasAt47Entry INT,
    BiasAt48Entry INT,
    BiasAt49Entry INT,
    BiasAt50Entry INT,
    BiasAt51Entry INT,
    BiasAt52Entry INT,
    BiasAt53Entry INT,
    BiasAt54Entry INT,
    BiasAt55Entry INT,
    BiasAt56Entry INT,
    BiasAt57Entry INT,
    BiasAt58Entry INT,
    BiasAt59Entry INT,
    BiasAt60Entry INT,
    BiasAt61Entry INT,
    BiasAt62Entry INT,
    BiasAt63Entry INT,
    BiasAt64Entry INT,
    BiasAt65Entry INT,
    BiasAt66Entry INT,
    BiasAt67Entry INT,
    BiasAt68Entry INT,
    BiasAt69Entry INT,
    BiasAt70Entry INT,
    BiasAt71Entry INT,
    BiasAt72Entry INT,
    BiasAt73Entry INT,
    BiasAt74Entry INT,
    BiasAt75Entry INT,
    BiasAt76Entry INT,
    BiasAt77Entry INT,
    BiasAt78Entry INT,
    BiasAt79Entry INT,
    BiasAt80Entry INT,
    BiasAt81Entry INT,
    BiasAt82Entry INT,
    BiasAt83Entry INT,
    BiasAt84Entry INT,
    BiasAt85Entry INT,
    BiasAt86Entry INT,
    BiasAt87Entry INT,
    BiasAt88Entry INT,
    BiasAt89Entry INT,
    BiasAt90Entry INT,
    BiasAt91Entry INT,
    BiasAt92Entry INT,
    BiasAt93Entry INT,
    BiasAt94Entry INT,
    BiasAt95Entry INT,
    BiasAt96Entry INT,
    BiasAt97Entry INT,
    BiasAt98Entry INT,
    BiasAt99Entry INT,
    BiasAt100Entry INT,
    BiasAt101Entry INT,
    BiasAt102Entry INT,
    BiasAt103Entry INT,
    BiasAt104Entry INT,
    BiasAt105Entry INT,
    BiasAt106Entry INT,
    BiasAt107Entry INT,
    BiasAt108Entry INT,
    BiasAt109Entry INT,
    BiasAt110Entry INT,
    BiasAt111Entry INT,
    BiasAt112Entry INT,
    BiasAt113Entry INT,
    BiasAt114Entry INT,
    BiasAt115Entry INT,
    BiasAt116Entry INT,
    BiasAt117Entry INT,
    BiasAt118Entry INT,
    BiasAt119Entry INT,
    BiasAt120Entry INT,
    BiasAt121Entry INT,
    BiasAt122Entry INT,
    BiasAt123Entry INT,
    BiasAt124Entry INT,
    BiasAt125Entry INT,
    BiasAt126Entry INT,
    BiasAt127Entry INT,
    BiasAt128Entry INT,
    BiasAt129Entry INT,
    BiasAt130Entry INT,
    BiasAt131Entry INT,
    BiasAt132Entry INT,
    BiasAt133Entry INT,
    BiasAt134Entry INT,
    BiasAt135Entry INT,
    BiasAt136Entry INT,
    BiasAt137Entry INT,
    BiasAt138Entry INT,
    BiasAt139Entry INT,
    BiasAt140Entry INT,
    BiasAt141Entry INT,
    BiasAt142Entry INT,
    BiasAt143Entry INT,
    BiasAt144Entry INT,
    BiasAt145Entry INT,
    BiasAt146Entry INT,
    BiasAt147Entry INT,
    BiasAt148Entry INT,
    BiasAt149Entry INT,
    BiasAt150Entry INT,
    BiasAt151Entry INT,
    BiasAt152Entry INT,
    BiasAt153Entry INT,
    BiasAt154Entry INT,
    BiasAt155Entry INT,
    BiasAt156Entry INT,
    BiasAt157Entry INT,
    BiasAt158Entry INT,
    BiasAt159Entry INT,
    BiasAt160Entry INT,
    BiasAt161Entry INT,
    BiasAt162Entry INT,
    BiasAt163Entry INT,
    BiasAt164Entry INT,
    BiasAt165Entry INT,
    BiasAt166Entry INT,
    BiasAt167Entry INT,
    BiasAt168Entry INT,
    BiasAt169Entry INT,
    BiasAt170Entry INT,
    BiasAt171Entry INT,
    BiasAt172Entry INT,
    BiasAt173Entry INT,
    BiasAt174Entry INT,
    BiasAt175Entry INT,
    BiasAt176Entry INT,
    BiasAt177Entry INT,
    BiasAt178Entry INT,
    BiasAt179Entry INT,
    BiasAt180Entry INT,
    BiasAt181Entry INT,
    BiasAt182Entry INT,
    BiasAt183Entry INT,
    BiasAt184Entry INT,
    BiasAt185Entry INT,
    BiasAt186Entry INT,
    BiasAt187Entry INT,
    BiasAt188Entry INT,
    BiasAt189Entry INT,
    BiasAt190Entry INT,
    BiasAt191Entry INT,
    BiasAt192Entry INT,
    BiasAt193Entry INT,
    BiasAt194Entry INT,
    BiasAt195Entry INT,
    BiasAt196Entry INT,
    BiasAt197Entry INT,
    BiasAt198Entry INT,
    BiasAt199Entry INT,
    BiasAt200Entry INT,
    BiasAt201Entry INT,
    BiasAt202Entry INT,
    BiasAt203Entry INT,
    BiasAt204Entry INT,
    BiasAt205Entry INT,
    BiasAt206Entry INT,
    BiasAt207Entry INT,
    BiasAt208Entry INT,
    BiasAt209Entry INT,
    BiasAt210Entry INT,
    BiasAt211Entry INT,
    BiasAt212Entry INT,
    BiasAt213Entry INT,
    BiasAt214Entry INT,
    BiasAt215Entry INT,
    BiasAt216Entry INT,
    BiasAt217Entry INT,
    BiasAt218Entry INT,
    BiasAt219Entry INT,
    BiasAt220Entry INT,
    BiasAt221Entry INT,
    BiasAt222Entry INT,
    BiasAt223Entry INT,
    BiasAt224Entry INT,
    BiasAt225Entry INT,
    BiasAt226Entry INT,
    BiasAt227Entry INT,
    BiasAt228Entry INT,
    BiasAt229Entry INT,
    BiasAt230Entry INT,
    BiasAt231Entry INT,
    BiasAt232Entry INT,
    BiasAt233Entry INT,
    BiasAt234Entry INT,
    BiasAt235Entry INT,
    BiasAt236Entry INT,
    BiasAt237Entry INT,
    BiasAt238Entry INT,
    BiasAt239Entry INT,
    BiasAt240Entry INT,
    BiasAt241Entry INT,
    BiasAt242Entry INT,
    BiasAt243Entry INT,
    BiasAt244Entry INT,
    BiasAt245Entry INT,
    BiasAt246Entry INT,
    BiasAt247Entry INT,
    BiasAt248Entry INT,
    BiasAt249Entry INT,
    BiasAt250Entry INT,
    BiasAt251Entry INT,
    BiasAt252Entry INT,
    BiasAt253Entry INT,
    BiasAt254Entry INT,
    BiasAt255Entry INT
);
CREATE TABLE AMPINFO(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL,
    AmpSet INT NOT NULL,
    -- Channel Info Table
    HG_Ped_MeanEntry INT NOT NULL UNIQUE,
    HG_Ped_StdDevEntry INT NOT NULL UNIQUE,
    LG_Ped_MeanEntry INT NOT NULL UNIQUE,
    LG_Ped_StdDevEntry INT NOT NULL UNIQUE,
    HG_Cali_ResultEntry INT NOT NULL UNIQUE,
    LG_Cali_ResultEntry INT NOT NULL UNIQUE
);
CREATE TABLE BIASINFO(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL,
    BiasSet INT NOT NULL,
    -- Channel Info Table
    BiasVoltageValueEntry INT NOT NULL
);
CREATE TABLE CHANNELSINFO(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL,
    Channel0Value REAL,
    Channel1Value REAL,
    Channel2Value REAL,
    Channel3Value REAL,
    Channel4Value REAL,
    Channel5Value REAL,
    Channel6Value REAL,
    Channel7Value REAL,
    Channel8Value REAL,
    Channel9Value REAL,
    Channel10Value REAL,
    Channel11Value REAL,
    Channel12Value REAL,
    Channel13Value REAL,
    Channel14Value REAL,
    Channel15Value REAL,
    Channel16Value REAL,
    Channel17Value REAL,
    Channel18Value REAL,
    Channel19Value REAL,
    Channel20Value REAL,
    Channel21Value REAL,
    Channel22Value REAL,
    Channel23Value REAL,
    Channel24Value REAL,
    Channel25Value REAL,
    Channel26Value REAL,
    Channel27Value REAL,
    Channel28Value REAL,
    Channel29Value REAL,
    Channel30Value REAL,
    Channel31Value REAL
);
CREATE TABLE SIPMBOARD(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL,
    BT INT NOT NULL CHECK(
        BT >= 0
        AND BT <= 1
    ),
    -- Temperature table Entry
    TemperatureTestGainEntry INT UNIQUE,
    -- Bias Table Entry
    BiasTestResultEntry INT UNIQUE,
    -- Channel Entry
    TSlopeEntry INT NOT NULL UNIQUE,
    BiasSlopeEntry INT NOT NULL UNIQUE,
    BDVoltageEntry INT NOT NULL UNIQUE,
    BDTemperatureEntry INT NOT NULL UNIQUE,
    TCompFactorEntry INT NOT NULL UNIQUE
);
CREATE TABLE TEMPERATURETESTTABLE(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL,
    BT INT NOT NULL CHECK(
        BT >= 0
        AND BT <= 1
    ),
    TemperatureTestPoints INT NOT NULL,
    T0TempEntry INT,
    T0Entry INT,
    T1TempEntry INT,
    T1Entry INT,
    T2TempEntry INT,
    T2Entry INT,
    T3TempEntry INT,
    T3Entry INT,
    T4TempEntry INT,
    T4Entry INT,
    T5TempEntry INT,
    T5Entry INT,
    T6TempEntry INT,
    T6Entry INT
);