PRAGMA foreign_keys = OFF;
-- BEGIN TRANSACTION;
ANALYZE sqlite_schema;
attach database 'F:\\Projects\\FEEDistri\\DataBase\\Calibration.db' as caliDB;
CREATE TABLE FEEBOARD(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL UNIQUE,
    Channel0EntryID INT NOT NULL,
    Channel1EntryID INT NOT NULL,
    Channel2EntryID INT NOT NULL,
    Channel3EntryID INT NOT NULL,
    Channel4EntryID INT NOT NULL,
    Channel5EntryID INT NOT NULL,
    Channel6EntryID INT NOT NULL,
    Channel7EntryID INT NOT NULL,
    Channel8EntryID INT NOT NULL,
    Channel9EntryID INT NOT NULL,
    Channel10EntryID INT NOT NULL,
    Channel11EntryID INT NOT NULL,
    Channel12EntryID INT NOT NULL,
    Channel13EntryID INT NOT NULL,
    Channel14EntryID INT NOT NULL,
    Channel15EntryID INT NOT NULL,
    Channel16EntryID INT NOT NULL,
    Channel17EntryID INT NOT NULL,
    Channel18EntryID INT NOT NULL,
    Channel19EntryID INT NOT NULL,
    Channel20EntryID INT NOT NULL,
    Channel21EntryID INT NOT NULL,
    Channel22EntryID INT NOT NULL,
    Channel23EntryID INT NOT NULL,
    Channel24EntryID INT NOT NULL,
    Channel25EntryID INT NOT NULL,
    Channel26EntryID INT NOT NULL,
    Channel27EntryID INT NOT NULL,
    Channel28EntryID INT NOT NULL,
    Channel29EntryID INT NOT NULL,
    Channel30EntryID INT NOT NULL,
    Channel31EntryID INT NOT NULL
);
CREATE TABLE ChannelEntry(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL,
    ChannelNo INT NOT NULL CHECK(
        ChannelNo >= 0
        AND ChannelNo < 32
    ),
    LG_Ped_Mean REAL,
    LG_Ped_Dev REAL,
    -- Entry in amp table
    LG_AMP_EntryID INT,
    HG_Ped_Mean REAL,
    HG_Ped_Dev REAL,
    -- Entry in amp table
    HG_AMP_EntryID INT,
    -- Entry in bias adc table
    Bias_ADC_EntryID INT
);
CREATE TABLE AmpTable(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT,
    ChannelNo INT,
    HGorLG INT,
    AmpAt0 REAL,
    AmpAt1 REAL,
    AmpAt2 REAL,
    AmpAt3 REAL,
    AmpAt4 REAL,
    AmpAt5 REAL,
    AmpAt6 REAL,
    AmpAt7 REAL,
    AmpAt8 REAL,
    AmpAt9 REAL,
    AmpAt10 REAL,
    AmpAt11 REAL,
    AmpAt12 REAL,
    AmpAt13 REAL,
    AmpAt14 REAL,
    AmpAt15 REAL,
    AmpAt16 REAL,
    AmpAt17 REAL,
    AmpAt18 REAL,
    AmpAt19 REAL,
    AmpAt20 REAL,
    AmpAt21 REAL,
    AmpAt22 REAL,
    AmpAt23 REAL,
    AmpAt24 REAL,
    AmpAt25 REAL,
    AmpAt26 REAL,
    AmpAt27 REAL,
    AmpAt28 REAL,
    AmpAt29 REAL,
    AmpAt30 REAL,
    AmpAt31 REAL,
    AmpAt32 REAL,
    AmpAt33 REAL,
    AmpAt34 REAL,
    AmpAt35 REAL,
    AmpAt36 REAL,
    AmpAt37 REAL,
    AmpAt38 REAL,
    AmpAt39 REAL,
    AmpAt40 REAL,
    AmpAt41 REAL,
    AmpAt42 REAL,
    AmpAt43 REAL,
    AmpAt44 REAL,
    AmpAt45 REAL,
    AmpAt46 REAL,
    AmpAt47 REAL,
    AmpAt48 REAL,
    AmpAt49 REAL,
    AmpAt50 REAL,
    AmpAt51 REAL,
    AmpAt52 REAL,
    AmpAt53 REAL,
    AmpAt54 REAL,
    AmpAt55 REAL,
    AmpAt56 REAL,
    AmpAt57 REAL,
    AmpAt58 REAL,
    AmpAt59 REAL,
    AmpAt60 REAL,
    AmpAt61 REAL,
    AmpAt62 REAL
);
CREATE TABLE BiasADCTable(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT,
    ChannelNo INT,
    BiasAt0 REAL,
    BiasAt1 REAL,
    BiasAt2 REAL,
    BiasAt3 REAL,
    BiasAt4 REAL,
    BiasAt5 REAL,
    BiasAt6 REAL,
    BiasAt7 REAL,
    BiasAt8 REAL,
    BiasAt9 REAL,
    BiasAt10 REAL,
    BiasAt11 REAL,
    BiasAt12 REAL,
    BiasAt13 REAL,
    BiasAt14 REAL,
    BiasAt15 REAL,
    BiasAt16 REAL,
    BiasAt17 REAL,
    BiasAt18 REAL,
    BiasAt19 REAL,
    BiasAt20 REAL,
    BiasAt21 REAL,
    BiasAt22 REAL,
    BiasAt23 REAL,
    BiasAt24 REAL,
    BiasAt25 REAL,
    BiasAt26 REAL,
    BiasAt27 REAL,
    BiasAt28 REAL,
    BiasAt29 REAL,
    BiasAt30 REAL,
    BiasAt31 REAL,
    BiasAt32 REAL,
    BiasAt33 REAL,
    BiasAt34 REAL,
    BiasAt35 REAL,
    BiasAt36 REAL,
    BiasAt37 REAL,
    BiasAt38 REAL,
    BiasAt39 REAL,
    BiasAt40 REAL,
    BiasAt41 REAL,
    BiasAt42 REAL,
    BiasAt43 REAL,
    BiasAt44 REAL,
    BiasAt45 REAL,
    BiasAt46 REAL,
    BiasAt47 REAL,
    BiasAt48 REAL,
    BiasAt49 REAL,
    BiasAt50 REAL,
    BiasAt51 REAL,
    BiasAt52 REAL,
    BiasAt53 REAL,
    BiasAt54 REAL,
    BiasAt55 REAL,
    BiasAt56 REAL,
    BiasAt57 REAL,
    BiasAt58 REAL,
    BiasAt59 REAL,
    BiasAt60 REAL,
    BiasAt61 REAL,
    BiasAt62 REAL,
    BiasAt63 REAL,
    BiasAt64 REAL,
    BiasAt65 REAL,
    BiasAt66 REAL,
    BiasAt67 REAL,
    BiasAt68 REAL,
    BiasAt69 REAL,
    BiasAt70 REAL,
    BiasAt71 REAL,
    BiasAt72 REAL,
    BiasAt73 REAL,
    BiasAt74 REAL,
    BiasAt75 REAL,
    BiasAt76 REAL,
    BiasAt77 REAL,
    BiasAt78 REAL,
    BiasAt79 REAL,
    BiasAt80 REAL,
    BiasAt81 REAL,
    BiasAt82 REAL,
    BiasAt83 REAL,
    BiasAt84 REAL,
    BiasAt85 REAL,
    BiasAt86 REAL,
    BiasAt87 REAL,
    BiasAt88 REAL,
    BiasAt89 REAL,
    BiasAt90 REAL,
    BiasAt91 REAL,
    BiasAt92 REAL,
    BiasAt93 REAL,
    BiasAt94 REAL,
    BiasAt95 REAL,
    BiasAt96 REAL,
    BiasAt97 REAL,
    BiasAt98 REAL,
    BiasAt99 REAL,
    BiasAt100 REAL,
    BiasAt101 REAL,
    BiasAt102 REAL,
    BiasAt103 REAL,
    BiasAt104 REAL,
    BiasAt105 REAL,
    BiasAt106 REAL,
    BiasAt107 REAL,
    BiasAt108 REAL,
    BiasAt109 REAL,
    BiasAt110 REAL,
    BiasAt111 REAL,
    BiasAt112 REAL,
    BiasAt113 REAL,
    BiasAt114 REAL,
    BiasAt115 REAL,
    BiasAt116 REAL,
    BiasAt117 REAL,
    BiasAt118 REAL,
    BiasAt119 REAL,
    BiasAt120 REAL,
    BiasAt121 REAL,
    BiasAt122 REAL,
    BiasAt123 REAL,
    BiasAt124 REAL,
    BiasAt125 REAL,
    BiasAt126 REAL,
    BiasAt127 REAL,
    BiasAt128 REAL,
    BiasAt129 REAL,
    BiasAt130 REAL,
    BiasAt131 REAL,
    BiasAt132 REAL,
    BiasAt133 REAL,
    BiasAt134 REAL,
    BiasAt135 REAL,
    BiasAt136 REAL,
    BiasAt137 REAL,
    BiasAt138 REAL,
    BiasAt139 REAL,
    BiasAt140 REAL,
    BiasAt141 REAL,
    BiasAt142 REAL,
    BiasAt143 REAL,
    BiasAt144 REAL,
    BiasAt145 REAL,
    BiasAt146 REAL,
    BiasAt147 REAL,
    BiasAt148 REAL,
    BiasAt149 REAL,
    BiasAt150 REAL,
    BiasAt151 REAL,
    BiasAt152 REAL,
    BiasAt153 REAL,
    BiasAt154 REAL,
    BiasAt155 REAL,
    BiasAt156 REAL,
    BiasAt157 REAL,
    BiasAt158 REAL,
    BiasAt159 REAL,
    BiasAt160 REAL,
    BiasAt161 REAL,
    BiasAt162 REAL,
    BiasAt163 REAL,
    BiasAt164 REAL,
    BiasAt165 REAL,
    BiasAt166 REAL,
    BiasAt167 REAL,
    BiasAt168 REAL,
    BiasAt169 REAL,
    BiasAt170 REAL,
    BiasAt171 REAL,
    BiasAt172 REAL,
    BiasAt173 REAL,
    BiasAt174 REAL,
    BiasAt175 REAL,
    BiasAt176 REAL,
    BiasAt177 REAL,
    BiasAt178 REAL,
    BiasAt179 REAL,
    BiasAt180 REAL,
    BiasAt181 REAL,
    BiasAt182 REAL,
    BiasAt183 REAL,
    BiasAt184 REAL,
    BiasAt185 REAL,
    BiasAt186 REAL,
    BiasAt187 REAL,
    BiasAt188 REAL,
    BiasAt189 REAL,
    BiasAt190 REAL,
    BiasAt191 REAL,
    BiasAt192 REAL,
    BiasAt193 REAL,
    BiasAt194 REAL,
    BiasAt195 REAL,
    BiasAt196 REAL,
    BiasAt197 REAL,
    BiasAt198 REAL,
    BiasAt199 REAL,
    BiasAt200 REAL,
    BiasAt201 REAL,
    BiasAt202 REAL,
    BiasAt203 REAL,
    BiasAt204 REAL,
    BiasAt205 REAL,
    BiasAt206 REAL,
    BiasAt207 REAL,
    BiasAt208 REAL,
    BiasAt209 REAL,
    BiasAt210 REAL,
    BiasAt211 REAL,
    BiasAt212 REAL,
    BiasAt213 REAL,
    BiasAt214 REAL,
    BiasAt215 REAL,
    BiasAt216 REAL,
    BiasAt217 REAL,
    BiasAt218 REAL,
    BiasAt219 REAL,
    BiasAt220 REAL,
    BiasAt221 REAL,
    BiasAt222 REAL,
    BiasAt223 REAL,
    BiasAt224 REAL,
    BiasAt225 REAL,
    BiasAt226 REAL,
    BiasAt227 REAL,
    BiasAt228 REAL,
    BiasAt229 REAL,
    BiasAt230 REAL,
    BiasAt231 REAL,
    BiasAt232 REAL,
    BiasAt233 REAL,
    BiasAt234 REAL,
    BiasAt235 REAL,
    BiasAt236 REAL,
    BiasAt237 REAL,
    BiasAt238 REAL,
    BiasAt239 REAL,
    BiasAt240 REAL,
    BiasAt241 REAL,
    BiasAt242 REAL,
    BiasAt243 REAL,
    BiasAt244 REAL,
    BiasAt245 REAL,
    BiasAt246 REAL,
    BiasAt247 REAL,
    BiasAt248 REAL,
    BiasAt249 REAL,
    BiasAt250 REAL,
    BiasAt251 REAL,
    BiasAt252 REAL,
    BiasAt253 REAL,
    BiasAt254 REAL,
    BiasAt255 REAL
);
CREATE TABLE SiPMBoard(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT NOT NULL,
    UporDown INT NOT NULL,
    SiPM0EntryID INT,
    SiPM1EntryID INT,
    SiPM2EntryID INT,
    SiPM3EntryID INT,
    SiPM4EntryID INT,
    SiPM5EntryID INT,
    SiPM6EntryID INT,
    SiPM7EntryID INT,
    SiPM8EntryID INT,
    SiPM9EntryID INT,
    SiPM10EntryID INT,
    SiPM11EntryID INT,
    SiPM12EntryID INT,
    SiPM13EntryID INT,
    SiPM14EntryID INT,
    SiPM15EntryID INT,
    SiPM16EntryID INT,
    SiPM17EntryID INT,
    SiPM18EntryID INT,
    SiPM19EntryID INT,
    SiPM20EntryID INT,
    SiPM21EntryID INT,
    SiPM22EntryID INT,
    SiPM23EntryID INT,
    SiPM24EntryID INT,
    SiPM25EntryID INT,
    SiPM26EntryID INT,
    SiPM27EntryID INT,
    SiPM28EntryID INT,
    SiPM29EntryID INT,
    SiPM30EntryID INT,
    SiPM31EntryID INT
);
CREATE TABLE SiPM(
    ID INT PRIMARY KEY NOT NULL,
    BoardNo INT,
    UporDown INT,
    BDVoltate REAL,
    -- Temperature factor: compensation voltage for 1 Celcius degree, unit is mV
    TemperatureFactor REAL,
    -- ADC value under 1V over voltage normalized to board 0 channel 0
    UnitADC REAL
);